name: Playwright Python Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Playwright Browsers
      run: playwright install --with-deps
    - name: Run pytest tests
      run: pytest tests/ -v --tb=short
      env:
        CI: true
        APP_URL: 'https://nikita-filonov.github.io/qa-automation-engineer-ui-course'
        HEADLESS: true
        BROWSERS: '["chromium"]'
        TEST_USER__EMAIL: 'user.name@gmail.com'
        TEST_USER__USERNAME: 'username'
        TEST_USER__PASSWORD: 'password'
        TEST_DATA__IMAGE_PNG_FILE: './testdata/files/image.png'
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          playwright-report/
          allure-results/
        retention-days: 30
